apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-backend-service-config
  namespace: dev
data:
  DEBUG: "True"
  DB_NAME: shopflow_cart
  DB_HOST: db_shopflow_carts
  DB_PORT: "3306"
  FRONTEND_URL: http://3.0.235.84:5173
  RESEND_FROM_EMAIL: "onboarding@resend.dev"
