apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-backend-service
  namespace:  dev
spec:
  minReadySeconds: 3
  # replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - cart-backend-service-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: cart-backend-service-pod
      labels:
        app: cart-backend-service-app
    spec:
      containers:
        - name: cart-backend-service
          image: 984912521466.dkr.ecr.ap-southeast-1.amazonaws.com/shopflow-cart-service-backend:1.0.1
          envFrom:
            - configMapRef:
                name: cart-backend-service-config
            - secretRef:
                name: cart-backend-service-secret
          imagePullPolicy:  Always

          startupProbe:
            httpGet:
              path: /api/cart/health/
              port: 8003
              httpHeaders:
                - name: Host
                  value: localhost
            failureThreshold: 30
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/cart/health/
              port: 8003
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /api/cart/health/
              port: 8003
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 5
            periodSeconds: 10

          ports:
            - containerPort:  8003
              protocol: TCP
          resources:
            requests:
              cpu: "50m"
              memory: "80Mi"
            limits:
              cpu: "80m"
              memory: "100Mi"