apiVersion: v1
kind: Service
metadata:
  name: cart-backend-service-svc-dp
  namespace: dev
spec:
  type: NodePort
  selector:
    app: cart-backend-service-app
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
      nodePort: 30003