apiVersion: v1
kind: Service

metadata:
  name: db_shopflow_home
  namespace: dev

spec:
  clusterIP: None

  selector:
    app: db_shopflow_home

  ports:
    - port: 3306
      nodePort: 3306
      protocol: TCP
