apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-backend-service-config
  namespace: dev
data:
  DEBUG: "True"
  DB_NAME: shopflow_profiles
  DB_HOST: db_shopflow_profiles
  DB_PORT: "3306"
  ALLOWED_HOSTS: "3.0.235.84,localhost,127.0.0.1,*"
  FRONTEND_URL: http://18.142.2.14:5173
  AUTH_SERVICE_URL: http://13.215.86.33:8000
  RESEND_FROM_EMAIL: "onboarding@resend.dev"
