apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-backend-service-config
  namespace: dev
data:
  DEBUG: True
  DB_NAME: shopflow_profiles
  DB_HOST: db_shopflow_profiles
  DB_PORT: 3306
  FRONTEND_URL: http://18.142.93.207:5173
  AUTH_SERVICE_URL: http://54.169.131.90:8000
  RESEND_FROM_EMAIL: onboarding@resend.dev
