apiVersion: v1
kind: Service

metadata:
  name: db-shopflow-profiles
  namespace: dev

spec:
  clusterIP: None

  selector:
    app: db-shopflow-profiles

  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
