apiVersion: v1
kind: Service
metadata:
  name: profile-backend-service-svc-dp
  namespace: dev
spec:
  type: NodePort
  selector:
    app: profile-backend-service-app
  ports:
    - port: 8005
      targetPort: 8005
      protocol: TCP
      nodePort: 30004