apiVersion: v1
kind: Service

metadata:
  name: db-shopflow-auth
  namespace: dev

spec:
  clusterIP: None

  selector:
    app: db-shopflow-auth

  ports:
    - port: 3306
      nodePort: 3306
      protocol: TCP
