apiVersion: v1
kind: Service
metadata:
  name: auth-backend-service-svc-dp
  namespace: dev
spec:
  type: NodePort
  selector:
    app: auth-backend-service-app
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30000